apiVersion: apps/v1
kind: Deployment
metadata:
  name: tp-cloud-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tp-cloud
  template:
    metadata:
      labels:
        app: tp-cloud
    spec:
      containers:
      - name: app
        image: europe-west1-docker.pkg.dev/tp-cloud-gke-nolan/tp-docker-repo/app:v1
        ports:
        - containerPort: 8080
